apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: akshayk6/devops-node-app:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

